# Generated by Django 5.1.6 on 2025-03-11 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_ingredient_recipeingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='description',
        ),
    ]
